### ISSUE TITLE
Microsoft Azure Storage Explorer cannot delete payload folder

### ISSUE THREAD

**Issue by markkenny** [autopkg/dataJAR-recipes#301]
com.github.dataJAR-recipes.pkg.MicrosoftAzureStorageExplorer

The download policy creates the Application folder, and the PKG recipe can delete that, but it errors on deleting the payload folder? Am I missing something?

**Comment by paul-cossey** [comment]
Hi, @markkenny 

Sorry for the slow reply on this, can you give this [commit](https://github.com/autopkg/dataJAR-recipes/commit/2cba49ead4471d27345586b54f1d49397fefa53d) a try please?

I've added in Graham Pugh's `ChangeModeOwner` processor to set the permissions so that  `pathdeleter` can actually delete the Applications folder. You'll need to add the following repo if you don't already have it. https://github.com/autopkg/grahampugh-recipes

**Comment by paul-cossey** [comment]
HI, @markkenny 

Did the above resolve this for you?

Thanks!

**Comment by markkenny** [comment]
Sorry for the slow reply too ;-)
Yes, recipe is running correctly for me. Thanks
